name: Formatting

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - '.github/workflows/format.yml'
      - 'Makefile'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/format.yml'
      - 'Makefile'
      - 'src/**'

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check Rust formatting
        run: cargo fmt -- --check
